export const TEAMS = [
  {
    id: 1,
    name: "Winner",
    players: [
      {
        id: 1,
        nickname: "Winner Player 1",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: true,
      },
      {
        id: 2,
        nickname: "Winner Player 2",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 3,
        nickname: "Winner Player 3",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 4,
        nickname: "Winner Player 4",
        points: 1312,
        isDead: false,
        kills: 111,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 5,
        nickname: "Winner Player 5",
        points: 323,
        isDead: true,
        kills: 313,
        deaths: 22,
        isInvited: true,
      },
      {
        id: 6,
        nickname: "Winner Player 6",
        points: 4234,
        isDead: true,
        kills: 44,
        deaths: 22,
        isInvited: false,
      },
      {
        id: 7,
        nickname: "Winner Player 7",
        points: 6161,
        isDead: false,
        kills: 3434,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 8,
        nickname: "Winner Player 8",
        points: 211,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 9,
        nickname: "Winner Player 9",
        points: 666,
        isDead: false,
        kills: 333,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 10,
        nickname: "Winner Player 10",
        points: 323,
        isDead: false,
        kills: 55,
        deaths: 1,
        isInvited: false,
      },
      {
        id: 11,
        nickname: "Winner Player 11",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: true,
      },
      {
        id: 12,
        nickname: "Winner Player 12",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 13,
        nickname: "Winner Player 13",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 14,
        nickname: "Winner Player 14",
        points: 1312,
        isDead: false,
        kills: 111,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 15,
        nickname: "Winner Player 15",
        points: 323,
        isDead: true,
        kills: 313,
        deaths: 22,
        isInvited: true,
      },
      {
        id: 16,
        nickname: "Winner Player 16",
        points: 4234,
        isDead: true,
        kills: 44,
        deaths: 22,
        isInvited: false,
      },
      {
        id: 17,
        nickname: "Winner Player 17",
        points: 6161,
        isDead: false,
        kills: 3434,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 18,
        nickname: "Winner Player 18",
        points: 211,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 19,
        nickname: "Winner Player 19",
        points: 666,
        isDead: false,
        kills: 333,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 20,
        nickname: "Winner Player 20",
        points: 323,
        isDead: false,
        kills: 55,
        deaths: 1,
        isInvited: false,
      },
      {
        id: 21,
        nickname: "Winner Player 21",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: true,
      },
      {
        id: 22,
        nickname: "Winner Player 22",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 23,
        nickname: "Winner Player 23",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 24,
        nickname: "Winner Player 24",
        points: 1312,
        isDead: false,
        kills: 111,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 25,
        nickname: "Winner Player 25",
        points: 323,
        isDead: true,
        kills: 313,
        deaths: 22,
        isInvited: true,
      },
      {
        id: 26,
        nickname: "Winner Player 26",
        points: 4234,
        isDead: true,
        kills: 44,
        deaths: 22,
        isInvited: false,
      },
      {
        id: 27,
        nickname: "Winner Player 27",
        points: 6161,
        isDead: false,
        kills: 3434,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 28,
        nickname: "Winner Player 28",
        points: 211,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 29,
        nickname: "Winner Player 29",
        points: 666,
        isDead: false,
        kills: 333,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 30,
        nickname: "Winner Player 30",
        points: 323,
        isDead: false,
        kills: 55,
        deaths: 1,
        isInvited: false,
      },
      {
        id: 31,
        nickname: "Winner Player 31",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: true,
      },
      {
        id: 32,
        nickname: "Winner Player 32",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 33,
        nickname: "Winner Player 33",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 34,
        nickname: "Winner Player 34",
        points: 1312,
        isDead: false,
        kills: 111,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 35,
        nickname: "Winner Player 35",
        points: 323,
        isDead: true,
        kills: 313,
        deaths: 22,
        isInvited: true,
      },
      {
        id: 36,
        nickname: "Winner Player 36",
        points: 4234,
        isDead: true,
        kills: 44,
        deaths: 22,
        isInvited: false,
      },
      {
        id: 37,
        nickname: "Winner Player 37",
        points: 6161,
        isDead: false,
        kills: 3434,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 38,
        nickname: "Winner Player 38",
        points: 211,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 39,
        nickname: "Winner Player 39",
        points: 666,
        isDead: false,
        kills: 333,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 40,
        nickname: "Winner Player 40",
        points: 323,
        isDead: false,
        kills: 55,
        deaths: 1,
        isInvited: false,
      },
      {
        id: 41,
        nickname: "Winner Player 41",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: true,
      },
      {
        id: 42,
        nickname: "Winner Player 42",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 43,
        nickname: "Winner Player 43",
        points: 100,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 44,
        nickname: "Winner Player 44",
        points: 1312,
        isDead: false,
        kills: 111,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 45,
        nickname: "Winner Player 45",
        points: 323,
        isDead: true,
        kills: 313,
        deaths: 22,
        isInvited: true,
      },
      {
        id: 46,
        nickname: "Winner Player 46",
        points: 4234,
        isDead: true,
        kills: 44,
        deaths: 22,
        isInvited: false,
      },
      {
        id: 47,
        nickname: "Winner Player 47",
        points: 6161,
        isDead: false,
        kills: 3434,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 48,
        nickname: "Winner Player 48",
        points: 211,
        isDead: false,
        kills: 10,
        deaths: 2,
        isInvited: false,
      },
      {
        id: 49,
        nickname: "Winner Player 49",
        points: 666,
        isDead: false,
        kills: 333,
        deaths: 222,
        isInvited: false,
      },
      {
        id: 50,
        nickname: "Winner Player 50",
        points: 323,
        isDead: false,
        kills: 55,
        deaths: 1,
        isInvited: false,
      },
    ],
  },
  {
    id: 2,
    name: "Loosing",
    players: [
      {
        id: 51,
        nickname: "Loosing Player 1",
        points: 100,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 52,
        nickname: "Loosing Player 2",
        points: 3141,
        isDead: false,
        kills: 32,
        deaths: 11,
        isInvited: false,
      },
      {
        id: 53,
        nickname: "Loosing Player 3",
        points: 6666,
        isDead: false,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 54,
        nickname: "Loosing Player 4",
        points: 1321,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 55,
        nickname: "Loosing Player 5",
        points: 6554,
        isDead: false,
        kills: 3434,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 56,
        nickname: "Loosing Player 6",
        points: 1,
        isDead: false,
        kills: 0,
        deaths: 0,
        isInvited: false,
      },
      {
        id: 57,
        nickname: "Loosing Player 7",
        points: 441,
        isDead: true,
        kills: 2,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 58,
        nickname: "Loosing Player 8",
        points: 100,
        isDead: false,
        kills: 4,
        deaths: 444,
        isInvited: false,
      },
      {
        id: 59,
        nickname: "Loosing Player 9",
        points: 87511,
        isDead: false,
        kills: 1,
        deaths: 1,
        isInvited: true,
      },
      {
        id: 60,
        nickname: "Loosing Player 10",
        points: 33,
        isDead: false,
        kills: 3,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 61,
        nickname: "Loosing Player 11",
        points: 100,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 62,
        nickname: "Loosing Player 12",
        points: 3141,
        isDead: false,
        kills: 32,
        deaths: 11,
        isInvited: false,
      },
      {
        id: 63,
        nickname: "Loosing Player 13",
        points: 6666,
        isDead: false,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 64,
        nickname: "Loosing Player 14",
        points: 1321,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 65,
        nickname: "Loosing Player 15",
        points: 6554,
        isDead: false,
        kills: 3434,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 66,
        nickname: "Loosing Player 16",
        points: 1,
        isDead: false,
        kills: 0,
        deaths: 0,
        isInvited: false,
      },
      {
        id: 67,
        nickname: "Loosing Player 17",
        points: 441,
        isDead: true,
        kills: 2,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 68,
        nickname: "Loosing Player 18",
        points: 100,
        isDead: false,
        kills: 4,
        deaths: 444,
        isInvited: false,
      },
      {
        id: 69,
        nickname: "Loosing Player 19",
        points: 87511,
        isDead: false,
        kills: 1,
        deaths: 1,
        isInvited: true,
      },
      {
        id: 70,
        nickname: "Loosing Player 20",
        points: 33,
        isDead: false,
        kills: 3,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 71,
        nickname: "Loosing Player 21",
        points: 100,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 72,
        nickname: "Loosing Player 22",
        points: 3141,
        isDead: false,
        kills: 32,
        deaths: 11,
        isInvited: false,
      },
      {
        id: 73,
        nickname: "Loosing Player 23",
        points: 6666,
        isDead: false,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 74,
        nickname: "Loosing Player 24",
        points: 1321,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 75,
        nickname: "Loosing Player 25",
        points: 6554,
        isDead: false,
        kills: 3434,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 76,
        nickname: "Loosing Player 26",
        points: 1,
        isDead: false,
        kills: 0,
        deaths: 0,
        isInvited: false,
      },
      {
        id: 77,
        nickname: "Loosing Player 27",
        points: 441,
        isDead: true,
        kills: 2,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 78,
        nickname: "Loosing Player 28",
        points: 100,
        isDead: false,
        kills: 4,
        deaths: 444,
        isInvited: false,
      },
      {
        id: 79,
        nickname: "Loosing Player 29",
        points: 87511,
        isDead: false,
        kills: 1,
        deaths: 1,
        isInvited: true,
      },
      {
        id: 80,
        nickname: "Loosing Player 30",
        points: 33,
        isDead: false,
        kills: 3,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 81,
        nickname: "Loosing Player 31",
        points: 100,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 82,
        nickname: "Loosing Player 32",
        points: 3141,
        isDead: false,
        kills: 32,
        deaths: 11,
        isInvited: false,
      },
      {
        id: 83,
        nickname: "Loosing Player 33",
        points: 6666,
        isDead: false,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 84,
        nickname: "Loosing Player 34",
        points: 1321,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 85,
        nickname: "Loosing Player 35",
        points: 6554,
        isDead: false,
        kills: 3434,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 86,
        nickname: "Loosing Player 36",
        points: 1,
        isDead: false,
        kills: 0,
        deaths: 0,
        isInvited: false,
      },
      {
        id: 87,
        nickname: "Loosing Player 37",
        points: 441,
        isDead: true,
        kills: 2,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 88,
        nickname: "Loosing Player 38",
        points: 100,
        isDead: false,
        kills: 4,
        deaths: 444,
        isInvited: false,
      },
      {
        id: 89,
        nickname: "Loosing Player 39",
        points: 87511,
        isDead: false,
        kills: 1,
        deaths: 1,
        isInvited: true,
      },
      {
        id: 90,
        nickname: "Loosing Player 40",
        points: 33,
        isDead: false,
        kills: 3,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 91,
        nickname: "Loosing Player 41",
        points: 100,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 92,
        nickname: "Loosing Player 42",
        points: 3141,
        isDead: false,
        kills: 32,
        deaths: 11,
        isInvited: false,
      },
      {
        id: 93,
        nickname: "Loosing Player 43",
        points: 6666,
        isDead: false,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 94,
        nickname: "Loosing Player 44",
        points: 1321,
        isDead: true,
        kills: 22,
        deaths: 13,
        isInvited: false,
      },
      {
        id: 95,
        nickname: "Loosing Player 45",
        points: 6554,
        isDead: false,
        kills: 3434,
        deaths: 33,
        isInvited: true,
      },
      {
        id: 96,
        nickname: "Loosing Player 46",
        points: 1,
        isDead: false,
        kills: 0,
        deaths: 0,
        isInvited: false,
      },
      {
        id: 97,
        nickname: "Loosing Player 47",
        points: 441,
        isDead: true,
        kills: 2,
        deaths: 31,
        isInvited: false,
      },
      {
        id: 98,
        nickname: "Loosing Player 48",
        points: 100,
        isDead: false,
        kills: 4,
        deaths: 444,
        isInvited: false,
      },
      {
        id: 99,
        nickname: "Loosing Player 49",
        points: 87511,
        isDead: false,
        kills: 1,
        deaths: 1,
        isInvited: true,
      },
      {
        id: 100,
        nickname: "Loosing Player 50",
        points: 33,
        isDead: false,
        kills: 3,
        deaths: 31,
        isInvited: false,
      },
    ],
  },
];
